---
title: "Developing Data Products: Week 2 Assignment"
author: "James Wright"
date: "21 December 2017"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## 60 Random Starbucks Locations in London

Date created: 21st December 2017

```{r, eval=TRUE, warning=FALSE}

library(leaflet)

dat = read.csv("C:/Users/james/OneDrive/Documents/Data Science/Data Science Online Course/9.Developing_Data_Products/Week2Assignment/DevelopingDataProducts_Week2_Assignment/LondonStarbucks.csv")

StarbucksLogo <- makeIcon("https://jamesawright.neocities.org/Starbucks-Logo.png",
                           iconWidth = 50*215/230, iconHeight = 50,
                           iconAnchorX = 31*215/230/2, iconAnchorY = 16
        
)

popups = dat$address

df <- data.frame(lat=dat['latitude'], lng=dat['longitude'])

my_map <- df %>% leaflet() %>% 
        addTiles() %>%
        addMarkers(icon=StarbucksLogo, popup=popups,
                   clusterOptions=markerClusterOptions())

my_map

```
